### ISSUE TITLE
New version design

### ISSUE THREAD

**Issue by Jinjiang** [weexteam/weex-vue-loader#2]
The new version is in branch `weex-next` which is forked from `vue-loader`. Based on web platform, weex-vue-loader make these changes below:

**parts**

* [x] `<template>`: use `weex-template-compiler`
* [x] `<style>`: use `weex-styler`
* [x] `<script>`: convert `require('@weex-module/xxx')`

**features**

* [x] no `isServer`
* [x] no `cssModules`
* [x] no `CssSourceMap`
* [x] no `isScoped`

**default**

* [x] `defaultLoaders`
  * [x] `lib/template-compiler`
    * [x] no `image[src]` conversion

**disabled temporarily**

* [x] no hot reload (adapt it later)
* [x] no functional render check (re-support it later)

**new option**

* [x] entry point config

**Comment by Hanks10100** [comment]
I have some additional ideas. In the loader, we can also do these:

+ Convert alias tag name.
+ Add lint rules.
+ Support semantic tags. Convert it to the similar (supported) tag with a default style.
+ If we support to write pulgins for `weex-template-compiler`, developer can write *"template syntactic sugar"*, which can be compiled in loader.
+ Support CSS preprocessors (and postcss).

**Comment by Jinjiang** [comment]
PostCSS has been supported in this loader. The other jobs can be done in weex-template-compiler or weex-styler instead. And it's possible to work with all packaging tools. The loader is just a connection to webpack.
