### ISSUE TITLE
How to use pug or jade

### ISSUE THREAD

**Issue by lzdyes** [weexteam/weex-vue-loader#22]
rt

**Comment by mdsb100** [comment]
waiting for new version.
just
```
<template lang="pug">
</template>
```

**Comment by mdsb100** [comment]
new version release

**Comment by Hanks10100** [comment]
It has already been supported and been integrated into the online playground. See this example http://dotwe.org/vue/25ede51ce3beb658380cd32fbc085d2e

**Comment by shinriyo** [comment]
```
Unhandled rejection Error: Cannot find module 'pug'
```
