### ISSUE TITLE
是不是0.7.x版本又不支持typescript了

### ISSUE THREAD

**Issue by zaaksam** [weexteam/weex-vue-loader#30]
0.6.x时提的PR修复的，刚刚升级到0.7.x，又不支持了。。。

**Comment by Hanks10100** [comment]
建议提供一些例子复现这个问题。

**Comment by xfront** [comment]
vue already support typescript, why not weex

**Comment by shinriyo** [comment]
It is standard to support TypeScript. how disappointing.
other one hope
https://github.com/alibaba/weex/issues/3092

however, if we customize it support. if I could I wanna do pull-request
https://my.oschina.net/zaaksam/blog/1572320

**Comment by Hanks10100** [comment]
Here is an example of using Typescript in Weex: https://github.com/Hanks10100/weex-typescript-example
