### ISSUE TITLE
What is the purpose of this, weex-loader and vue-loader?

### ISSUE THREAD

**Issue by n3ps** [weexteam/weex-vue-loader#34]
Is it possible to simplify? 

Use the new vue-loader and make this a vue-loader "plugin"?

**Comment by Hanks10100** [comment]
Refer to this comment: https://github.com/weexteam/weex-loader/issues/69#issuecomment-395652576

> The `weex-vue-loader` offers an equivalent function with `vue-loader` but only for the Weex platform. To be pecific. it's a webpack loader whick can be used to compile the `*.vue` files into `*.js` files for Weex platfrom.
