### ISSUE TITLE
how to use stylus

### ISSUE THREAD

**Issue by zfha** [weexteam/weex-vue-loader#7]
In Vue-loader, I can use stylus, the same config not used in weex-vue-loader.
I follow the source code. From weex-loader to weex-vue-loader, but i then don't know how to use.
please give me an example to do it! 
My webpack config is
```
module: {
      loaders: [
        {
          test: /\.js$/,
          loader: 'babel',
          exclude: /node_modules/
        }, {
          test: /\.vue(\?[^?]+)?$/,
          loaders: ['weex'],
        }
      ]
    },
vue: {
      loaders: {
        stylus: 'css?sourceMap!stylus'
      }
}
```

THASNK!

**Comment by dts** [comment]
I got SCSS to work with this:
```
{
  test: /\.vue(\?[^?]+)?$/,
  loaders: 'weex-loader',
  options: {
    loaders: {
      'scss': ['weex-vue-loader/lib/style-loader','sass-loader']
    }
  }
}
```

You might try that, but replacing the 'scss' and 'sass' with 'stylus'.  This is with Webpack 2 BTW.

**Comment by cho-is** [comment]
follow same instructions a [vue-loader](http://vue-loader.vuejs.org/en/configurations/pre-processors.html)

**Comment by chogarcia** [comment]
for me following same instructions a [vue-loader](http://vue-loader.vuejs.org/en/configurations/pre-processors.html) works

**Comment by jefflindholm** [comment]
I have tried a number of things here, when I use the vue-loader for the web page it works fine
but weex I get **Module not found: Error: Cannot resolve module 'scss-loader'**
```    test: /\.vue(\?[^?]+)?$/, 
    loader: 'weex-loader',
    options: {
        loaders: {
            'scss': 'weex-style-loader!css-loader!sass-loader',
            // 'scss': ['weex-vue-loader/lib/style-loader','sass-loader']
        }
    }
    // options: {
    //     loaders: {
    //         scss: [
    //             'weex-css-loader',
    //             'sass-loader',
    //         ]
    //     }
    // }
```
Anyone got any ideas? Thanks

**Comment by erha19** [comment]
Pr:https://github.com/weexteam/weex-vue-loader/pull/14
You can use `stylus` by:
```
{
  test: /\.vue(\?[^?]+)?$/,
  loaders: 'weex-loader',
  options: {
    loaders: {
      'stylus': ['stylus-loader']
    }
  }
}
```
