### ISSUE TITLE
Tag close bug

### ISSUE THREAD

**Issue by songsiqi** [weexteam/weex-vue-loader#8]
I must use `/` to close `<input>` tag:

```
<input type="text" class="input" placeholder="please input" />
```

Otherwise the vdom could not be generated.

```
<input type="text" class="input" placeholder="please input">
```

But browsers allow us to omit `/`.

**Comment by Hanks10100** [comment]
I have already send a PR to fix this. https://github.com/vuejs/vue/pull/5052
